classes:
  miner:
    haste:
      amplifier: 0
    healthBoost:
      amplifier: 1
  fisherman:
    night:
      amplifier: 0
    healthBoost:
      amplifier: 1
  timberman:
    wood:
      multiplier: 2.0
    strength:
      amplifier: 0
    healthBoost:
      amplifier: 1