name: BasicMMO
version: 1.3
main: com.rs.basicMMO.BasicMMO
api-version: 1.21
author: inmisin
description: A basic MMO-like class and skill plugin.

commands:
  mmo:
    description: BasicMMO main command.
    usage: /<command> [help|info|class|reload]
    aliases: [mm, m]
  takexp:
    description: Adds experience points in exchange for emeralds.
    usage: /<command>