name: BasicMMO
main: com.rs.basicMMO.BasicMMO
version: 1.2
api-version: "1.21"
commands:
  chooseClass:
    description: Sınıf seçimini yapar.
    usage: /chooseclass <className>
  levelUp:
    description: Seviye atlamayı gerçekleştirir.
    usage: /levelup
  levelInfo:
    description: XP ve seviye bilgilerini görüntüler.
    usage: /levelinfo
  classReload:
    description: Sınıf efektlerini yeniden yükler.
    usage: /classreload
  BasicMMO:
    description: Yardım menüsünü gösterir.
    usage: /basicMMO
  takeXp:
    description: Zümrüt karşılığında xp kazanırsın.
    usage: /takexp
  skills:
    description: Test
    usage: /skills